version: "3"

services: 
    db:
        image: mysql:5.7
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE
            - MYSQL_ALLOW_EMPTY_PASSWORD
    dev:
        image: mcr.microsoft.com/dotnet/sdk:5.0
        working_dir: /app
        volumes:
            - ./app:/app
        depends_on: 
            - db
        profiles:
            - dev
    web:
        build: 
            context: ./app
        depends_on: 
            - db
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 5s
    nginx:
        build: 
            context: ./nginx
        ports: 
            - 8000:80
        depends_on: 
            web:
                condition: "service_healthy"
          
