version: "3"

services: 
    db:
        image: mysql:5.7
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE
            - MYSQL_ALLOW_EMPTY_PASSWORD
        networks: 
            - desafio-pfa-docker-back
    dev:
        image: mcr.microsoft.com/dotnet/sdk:5.0
        working_dir: /app
        volumes:
            - ./app:/app
        depends_on: 
            - db
        profiles:
            - dev
    web:
        build: 
            context: ./app
        depends_on: 
            - db
        networks: 
            - desafio-pfa-docker-back
            - desafio-pfa-docker-front
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 20s
            retries: 6
            start_period: 10s
    nginx:
        build: 
            context: ./nginx
        ports: 
            - 8000:80
            - 8080:80
        networks: 
            - desafio-pfa-docker-front
        depends_on: 
            web:
                condition: "service_healthy"
          
networks: 
    desafio-pfa-docker-back:
        driver: 
            bridge
    desafio-pfa-docker-front:
        driver: 
            bridge