version: "3"

services: 
    db:
        image: mysql:5.7
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE
            - MYSQL_ALLOW_EMPTY_PASSWORD
    dev:
        image: mcr.microsoft.com/dotnet/sdk:5.0
        working_dir: /app
        volumes:
            - ./app:/app
        depends_on: 
            - db
        profiles:
            - dev
    web:
        build: 
            context: ./app
        ports:
            - 8080:80
        depends_on: 
            - db
